# Generated by Django 3.1.2 on 2020-11-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='armazon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='enfoque',
            field=models.CharField(choices=[('L', 'Lejos'), ('C', 'Cerca')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='lado',
            field=models.CharField(choices=[('I', 'Izqierda'), ('D', 'Derecha')], default=None, max_length=1, null=True),
        ),
    ]
