# Generated by Django 3.1.3 on 2020-11-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20201129_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='observacion',
        ),
        migrations.AddField(
            model_name='consulta',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.turnos'),
        ),
    ]
