# Generated by Django 3.1.3 on 2020-11-29 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_auto_20201129_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observacion',
            old_name='Turno',
            new_name='Consulta',
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='Observacion',
        ),
        migrations.AddField(
            model_name='consulta',
            name='observaciones',
            field=models.ManyToManyField(to='clinica.Observacion', verbose_name='Observacion'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='Consulta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.consulta'),
        ),
    ]
