# Generated by Django 3.1.3 on 2020-11-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_auto_20201129_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='consulta',
            name='observaciones',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Observacion',
        ),
    ]
