# Generated by Django 3.1.3 on 2020-11-30 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0008_auto_20201129_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='turno',
        ),
        migrations.AddField(
            model_name='turnos',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.consulta'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='Paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turnos',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.user'),
            preserve_default=False,
        ),
    ]
