# Generated by Django 3.1.3 on 2020-11-30 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_auto_20201130_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='consulta',
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente'),
            preserve_default=False,
        ),
    ]
