# Generated by Django 3.1.2 on 2020-11-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('clinica', '0009_auto_20201122_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('T', 'Tarjeta de credito'), ('B', 'Billetera virtual'), ('E', 'Efectivo'), ('D', 'Debito')], default='E', max_length=1)),
                ('estado', models.CharField(choices=[('PT', 'Pendiente'), ('PD', 'Pedido'), ('TL', 'Taller'), ('FP', 'Finalizado')], default='PD', max_length=2)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_perfiltaller', to='usuarios.perfilventas')),
            ],
        ),
    ]
