# Generated by Django 3.1.2 on 2020-11-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_auto_20201122_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_venta',
            new_name='fecha',
        ),
    ]
