# Generated by Django 3.1.2 on 2020-11-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0012_auto_20201122_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha',
        ),
    ]
