# Generated by Django 3.1.2 on 2020-11-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0014_pedido_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(default=None),
        ),
    ]
