# Generated by Django 3.1.2 on 2020-11-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0016_auto_20201122_1546'),
        ('clinica', '0012_consulta_paciente'),
    ]

    operations = [
    ]
