# Generated by Django 3.1.2 on 2020-11-22 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0017_merge_20201122_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinica_paciente', to='clinica.paciente'),
        ),
    ]
