# Generated by Django 3.1.2 on 2020-11-23 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0017_merge_20201122_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinica_paciente.nombre+', to='clinica.paciente'),
        ),
    ]
