# Generated by Django 3.1.2 on 2020-11-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0018_auto_20201123_1020'),
        ('clinica', '0019_auto_20201123_0940'),
    ]

    operations = [
    ]
