# Generated by Django 3.1.3 on 2020-11-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0021_auto_20201125_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='asistencia',
            field=models.CharField(blank=True, choices=[('P', 'Pendiente'), ('A', 'Asistió'), ('F', 'Faltó')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='HoraTurno',
            field=models.TimeField(),
        ),
    ]
