# Generated by Django 3.1.3 on 2020-11-25 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0021_auto_20201123_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaTurno', models.DateField()),
                ('HoraTurno', models.DateTimeField()),
                ('FechaAlta', models.DateField()),
                ('FechaBaja', models.DateField()),
                ('Paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinica_pacienteId', to='clinica.paciente')),
            ],
        ),
    ]
