# Generated by Django 3.1.3 on 2020-11-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0021_auto_20201123_1539'),
        ('clinica', '0023_auto_20201125_1454'),
        ('clinica', '0022_auto_20201126_0600'),
    ]

    operations = [
    ]
