# Generated by Django 3.1.3 on 2020-11-27 03:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0024_merge_20201127_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PT', 'Pendiente'), ('PD', 'Pedido'), ('TL', 'Taller')], default='PD', max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 11, 27, 3, 34, 3, 73939, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('L', 'Lente'), ('E', 'Estuche'), ('G', 'Gotita')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='FechaAlta',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='FechaBaja',
            field=models.DateField(blank=True),
        ),
    ]
