# Generated by Django 3.1.3 on 2020-11-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0025_auto_20201126_1303'),
        ('clinica', '0025_auto_20201127_0034'),
    ]

    operations = [
    ]
