# Generated by Django 3.1.2 on 2020-11-28 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0028_auto_20201128_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='FechaAlta',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='FechaBaja',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PT', 'Pendiente'), ('PD', 'Pedido'), ('TL', 'Taller'), ('FN', 'Finalizado')], default='PD', max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 16, 26, 49, 482393, tzinfo=utc)),
        ),
    ]
