# Generated by Django 3.1.2 on 2020-11-28 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0029_auto_20201128_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 16, 32, 15, 449768, tzinfo=utc)),
        ),
    ]
