# Generated by Django 3.1.3 on 2020-11-28 18:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0029_auto_20201128_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='doctor',
            new_name='medico',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 18, 4, 44, 880349, tzinfo=utc)),
        ),
    ]
