# Generated by Django 3.1.2 on 2020-11-28 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0030_auto_20201128_1504'),
        ('clinica', '0030_auto_20201128_1332'),
    ]

    operations = [
    ]
