# Generated by Django 3.1.2 on 2020-11-29 00:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0032_auto_20201128_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidodetalle',
            old_name='total',
            new_name='precio',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 11, 29, 0, 49, 22, 859070, tzinfo=utc)),
        ),
    ]
