# Generated by Django 3.1.3 on 2020-11-29 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0032_auto_20201128_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='medico',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 11, 29, 16, 51, 49, 392653, tzinfo=utc)),
        ),
    ]
