# Generated by Django 3.1.2 on 2020-11-29 03:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0034_auto_20201128_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='FechaBaja',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 11, 29, 3, 27, 13, 542695, tzinfo=utc)),
        ),
    ]
