# Generated by Django 3.1.2 on 2020-11-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0035_auto_20201129_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
