# Generated by Django 3.1.2 on 2020-11-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('clinica', '0036_auto_20201129_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('L', 'Lente'), ('E', 'Estuche'), ('G', 'Gotita'), ('A', 'Accesorios')], default='L', max_length=1),
        ),
    ]
