# Generated by Django 3.1.3 on 2020-11-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0033_auto_20201129_1351'),
        ('clinica', '0036_auto_20201129_0955'),
    ]

    operations = [
    ]
