# Generated by Django 3.1.3 on 2020-11-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0037_merge_20201129_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('L', 'Lente'), ('E', 'Estuche'), ('G', 'Gotita'), ('A', 'Accesorios')], default='L', max_length=1),
        ),
    ]
