# Generated by Django 3.1.2 on 2020-11-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0019_auto_20201123_0940'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmedico',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perfilsecretaria',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perfiltaller',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perfilventas',
            name='user',
        ),
        migrations.DeleteModel(
            name='PerfilGerencia',
        ),
        migrations.DeleteModel(
            name='PerfilMedico',
        ),
        migrations.DeleteModel(
            name='PerfilSecretaria',
        ),
        migrations.DeleteModel(
            name='PerfilTaller',
        ),
        migrations.DeleteModel(
            name='PerfilVentas',
        ),
    ]
