# Generated by Django 3.1.2 on 2020-12-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmedico',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perfilsecretaria',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perfiltaller',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perfilventas',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PerfilGerencia',
        ),
        migrations.DeleteModel(
            name='PerfilMedico',
        ),
        migrations.DeleteModel(
            name='PerfilSecretaria',
        ),
        migrations.DeleteModel(
            name='PerfilTaller',
        ),
        migrations.DeleteModel(
            name='PerfilVentas',
        ),
    ]
