<<<<<<< HEAD:Tpclinica/usuarios/migrations/0002_auto_20201201_0721.py
# Generated by Django 3.1.3 on 2020-12-01 10:21
=======
# Generated by Django 3.1.2 on 2020-12-01 01:13
>>>>>>> c3aa2814007e43d3d7cdf3216547162276266c50:Tpclinica/usuarios/migrations/0002_auto_20201130_2213.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmedico',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perfilsecretaria',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perfiltaller',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perfilventas',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PerfilGerencia',
        ),
        migrations.DeleteModel(
            name='PerfilMedico',
        ),
        migrations.DeleteModel(
            name='PerfilSecretaria',
        ),
        migrations.DeleteModel(
            name='PerfilTaller',
        ),
        migrations.DeleteModel(
            name='PerfilVentas',
        ),
    ]
